package gui.menu;


import dados.LSetBook;
import dados.*;
import gui.modeloDesign.AnimateBTT;
import java.util.ArrayList;
import negocio.Fachada;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;




public class MenuOption extends javax.swing.JFrame {
    
    //FACHADA
    Fachada fachada = new Fachada();
    Set<Carro> carros = ((RepoCarro) fachada.get("carros")).src();
    Set<Aluguel> alugueis = ((RepoAluguel) fachada.get("alugueis")).src();
    Set<Manutencao> manutencoes = ((RepoManutencao) fachada.get("manutencoes")).src();
    Set<Cliente> clientes = ((RepoCliente) fachada.get("clientes")).src();
    
    AnimateBTT ColorOP = new AnimateBTT();

			
    public MenuOption() {
        initComponents();
        addRowToTableFrota();

        // Adicionar um ListSelectionListener à TableFrota
        TableFrota.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                // Verificar se a seleção não está em ajuste (evita duplicação de eventos)
                if (!event.getValueIsAdjusting()) {
                    // Obter a linha selecionada
                    int selectedRow = TableFrota.getSelectedRow();

                    // Verificar se uma linha foi selecionada
                    if (selectedRow != -1) {
                        // Recuperar os dados da linha selecionada
                        String marca = (String) TableFrota.getValueAt(selectedRow, 0);
                        String modelo = (String) TableFrota.getValueAt(selectedRow, 1);
                        String placa = (String) TableFrota.getValueAt(selectedRow, 2);
                        String ano = TableFrota.getValueAt(selectedRow, 3).toString();
                        String valor = TableFrota.getValueAt(selectedRow, 4).toString();
                        String estado = (String) TableFrota.getValueAt(selectedRow, 5);

                        // Preencher os campos de texto com os dados da linha selecionada
                        TFMarca.setText(marca);
                        TFModelo.setText(modelo);
                        TFPlaca.setText(placa);
                        TFAno.setText(ano);
                        TFValor.setText(valor);
                        TFEstado.setSelectedItem(estado);
                   } 
                }
            }
        });
    }
   
    public void addRowToTableFrota(){
        DefaultTableModel model = (DefaultTableModel) TableFrota.getModel();
        Set<Carro> list = carros;
        model.setRowCount(0);
        TableFrota.revalidate();
        Object rowData[] = new Object[6];
        for(Carro carro : list){
            rowData[0] = carro.get("marca");
            rowData[1] = carro.get("modelo");
            rowData[2] = carro.get("placa");
            rowData[3] = carro.get("ano");
            rowData[4] = carro.get("valor");
            rowData[5] = carro.get("estado");
            model.addRow(rowData);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btt_frota = new gui.componentes.PanelGradient();
        lbl_frota = new javax.swing.JLabel();
        btt_manutencao = new gui.componentes.PanelGradient();
        lbl_manuntencao = new javax.swing.JLabel();
        btt_clientes = new gui.componentes.PanelGradient();
        lbl_clientes = new javax.swing.JLabel();
        btt_sair = new gui.componentes.PanelGradient();
        lbl_sair = new javax.swing.JLabel();
        abasMenu = new javax.swing.JTabbedPane();
        pageFrota = new javax.swing.JPanel();
        fPainelFrota = new Panel_redondo.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableFrota = new javax.swing.JTable();
        TSearchFrota = new javax.swing.JTextField();
        fPainelFiltro = new Panel_redondo.PanelRound();
        lblMarca = new javax.swing.JLabel();
        TFMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        TFModelo = new javax.swing.JTextField();
        lblPlacaa = new javax.swing.JLabel();
        TFPlaca = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        TFAno = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        TFValor = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        TFEstado = new javax.swing.JComboBox<>();
        FbttnSalvar = new Panel_redondo.PanelRound();
        FlblSalvar = new javax.swing.JLabel();
        TSFrotaClear = new javax.swing.JPanel();
        FiconeTitulo = new gui.componentes.PanelGradient();
        FTitulo = new javax.swing.JLabel();
        FTitulo1 = new javax.swing.JLabel();
        FbttnDeletar = new Panel_redondo.PanelRound();
        FlblDeletar = new javax.swing.JLabel();
        pageManuntencao = new javax.swing.JPanel();
        panelRound2 = new Panel_redondo.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableFrota1 = new javax.swing.JTable();
        pageClientes = new javax.swing.JPanel();
        panelRound3 = new Panel_redondo.PanelRound();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableFrota2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(109, 26, 54));
        Menu.setMinimumSize(new java.awt.Dimension(200, 720));
        Menu.setPreferredSize(new java.awt.Dimension(200, 720));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LocaRec");
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btt_frota.setBackground(new java.awt.Color(109, 26, 54));
        btt_frota.setColorGradient(new java.awt.Color(109, 26, 54));
        btt_frota.setMinimumSize(new java.awt.Dimension(178, 32));
        btt_frota.setRadius(20);
        btt_frota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btt_frotaMousePressed(evt);
            }
        });
        btt_frota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_frota.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lbl_frota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carro32px.png"))); // NOI18N
        lbl_frota.setText("       Frota");
        lbl_frota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_frotaMousePressed(evt);
            }
        });
        btt_frota.add(lbl_frota, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 170, 32));

        Menu.add(btt_frota, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 290, 188, 32));

        btt_manutencao.setBackground(new java.awt.Color(109, 26, 54));
        btt_manutencao.setColorGradient(new java.awt.Color(109, 26, 54));
        btt_manutencao.setRadius(20);
        btt_manutencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btt_manutencaoMousePressed(evt);
            }
        });
        btt_manutencao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manuntencao.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lbl_manuntencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/rep32px.png"))); // NOI18N
        lbl_manuntencao.setText("      Manuntenção");
        lbl_manuntencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_manuntencaoMousePressed(evt);
            }
        });
        btt_manutencao.add(lbl_manuntencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 32));

        Menu.add(btt_manutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 330, 188, 32));

        btt_clientes.setBackground(new java.awt.Color(109, 26, 54));
        btt_clientes.setColorGradient(new java.awt.Color(109, 26, 54));
        btt_clientes.setRadius(20);
        btt_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btt_clientesMousePressed(evt);
            }
        });
        btt_clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_clientes.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lbl_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cliente32px.png"))); // NOI18N
        lbl_clientes.setText("      Clientes");
        lbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_clientesMousePressed(evt);
            }
        });
        btt_clientes.add(lbl_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 170, 32));

        Menu.add(btt_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 370, 188, 32));

        btt_sair.setBackground(new java.awt.Color(153, 153, 153));
        btt_sair.setColorGradient(new java.awt.Color(102, 102, 102));
        btt_sair.setRadius(20);
        btt_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btt_sairMousePressed(evt);
            }
        });
        btt_sair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sair.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        lbl_sair.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sair.setText("SAIR");
        lbl_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_sairMousePressed(evt);
            }
        });
        btt_sair.add(lbl_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 170, 32));

        Menu.add(btt_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 680, 188, 32));

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        abasMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pageFrota.setBackground(new java.awt.Color(255, 255, 255));
        pageFrota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fPainelFrota.setBackground(new java.awt.Color(230, 232, 230));
        fPainelFrota.setAlignmentX(2.0F);
        fPainelFrota.setAlignmentY(2.0F);
        fPainelFrota.setRoundBottomLeft(25);
        fPainelFrota.setRoundBottomRight(25);
        fPainelFrota.setRoundTopLeft(25);

        TableFrota.setBackground(new java.awt.Color(255, 255, 255));
        TableFrota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Placa", "Ano", "Valor", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableFrota.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TableFrota);

        javax.swing.GroupLayout fPainelFrotaLayout = new javax.swing.GroupLayout(fPainelFrota);
        fPainelFrota.setLayout(fPainelFrotaLayout);
        fPainelFrotaLayout.setHorizontalGroup(
            fPainelFrotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPainelFrotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        fPainelFrotaLayout.setVerticalGroup(
            fPainelFrotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPainelFrotaLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pageFrota.add(fPainelFrota, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 480));

        TSearchFrota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSearchFrotaActionPerformed(evt);
            }
        });
        pageFrota.add(TSearchFrota, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 300, 30));

        fPainelFiltro.setBackground(new java.awt.Color(230, 232, 230));
        fPainelFiltro.setMinimumSize(new java.awt.Dimension(340, 480));
        fPainelFiltro.setRoundBottomLeft(25);
        fPainelFiltro.setRoundBottomRight(25);
        fPainelFiltro.setRoundTopLeft(25);
        fPainelFiltro.setRoundTopRight(25);
        fPainelFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMarca.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblMarca.setText("Marca*");
        fPainelFiltro.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 70, 20));

        TFMarca.setBackground(new java.awt.Color(255, 255, 255));
        fPainelFiltro.add(TFMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 30));

        lblModelo.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblModelo.setText("Modelo*");
        fPainelFiltro.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 20));

        TFModelo.setBackground(new java.awt.Color(255, 255, 255));
        fPainelFiltro.add(TFModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, 30));

        lblPlacaa.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblPlacaa.setText("Placa*");
        fPainelFiltro.add(lblPlacaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 70, 20));

        TFPlaca.setBackground(new java.awt.Color(255, 255, 255));
        fPainelFiltro.add(TFPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, 30));

        lblAno.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblAno.setText("Ano*");
        fPainelFiltro.add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 70, 20));

        TFAno.setBackground(new java.awt.Color(255, 255, 255));
        fPainelFiltro.add(TFAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 80, 30));

        lblValor.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblValor.setText("Valor*");
        fPainelFiltro.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 70, 20));

        TFValor.setBackground(new java.awt.Color(255, 255, 255));
        fPainelFiltro.add(TFValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 100, 30));

        lblEstado.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblEstado.setText("Estado*");
        fPainelFiltro.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 70, 20));

        TFEstado.addItem("Disponivel");
        TFEstado.setBackground(new java.awt.Color(255, 255, 255));
        TFEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponivel", "Alugado", "Em Manutenção" }));
        TFEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEstadoActionPerformed(evt);
            }
        });
        fPainelFiltro.add(TFEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 120, -1));

        pageFrota.add(fPainelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 340, 410));

        FbttnSalvar.setBackground(new java.awt.Color(255, 102, 102));
        FbttnSalvar.setRoundBottomLeft(20);
        FbttnSalvar.setRoundBottomRight(20);
        FbttnSalvar.setRoundTopLeft(20);
        FbttnSalvar.setRoundTopRight(20);
        FbttnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FbttnSalvarMousePressed(evt);
            }
        });
        FbttnSalvar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlblSalvar.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        FlblSalvar.setForeground(new java.awt.Color(255, 255, 255));
        FlblSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FlblSalvar.setText("Salvar");
        FbttnSalvar.add(FlblSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 20));

        pageFrota.add(FbttnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 180, 40));

        TSFrotaClear.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout TSFrotaClearLayout = new javax.swing.GroupLayout(TSFrotaClear);
        TSFrotaClear.setLayout(TSFrotaClearLayout);
        TSFrotaClearLayout.setHorizontalGroup(
            TSFrotaClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        TSFrotaClearLayout.setVerticalGroup(
            TSFrotaClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pageFrota.add(TSFrotaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 90, 30, 30));

        FiconeTitulo.setBackground(new java.awt.Color(153, 0, 0));
        FiconeTitulo.setColorGradient(new java.awt.Color(255, 51, 51));
        FiconeTitulo.setGradientType(gui.componentes.PanelGradient.GradientType.DIAGONAL_1);
        FiconeTitulo.setMinimumSize(new java.awt.Dimension(64, 64));
        FiconeTitulo.setRadius(20);
        pageFrota.add(FiconeTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 64, 64));

        FTitulo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        FTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FTitulo.setText("Gerencie os seus carros aqui!");
        pageFrota.add(FTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 270, 20));

        FTitulo1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        FTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FTitulo1.setText("Gerenciador de Frota!");
        pageFrota.add(FTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 270, 30));

        FbttnDeletar.setBackground(new java.awt.Color(255, 102, 102));
        FbttnDeletar.setRoundBottomLeft(20);
        FbttnDeletar.setRoundBottomRight(20);
        FbttnDeletar.setRoundTopLeft(20);
        FbttnDeletar.setRoundTopRight(20);
        FbttnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FbttnDeletarMousePressed(evt);
            }
        });
        FbttnDeletar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlblDeletar.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        FlblDeletar.setForeground(new java.awt.Color(255, 255, 255));
        FlblDeletar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FlblDeletar.setText("Deletar");
        FbttnDeletar.add(FlblDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 20));

        pageFrota.add(FbttnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 180, 40));

        abasMenu.addTab("tab1", pageFrota);

        panelRound2.setBackground(new java.awt.Color(230, 232, 230));
        panelRound2.setAlignmentX(2.0F);
        panelRound2.setAlignmentY(2.0F);

        TableFrota1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Placa", "Ano", "Valor", "Estado", "Disponível?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableFrota1);
        if (TableFrota1.getColumnModel().getColumnCount() > 0) {
            TableFrota1.getColumnModel().getColumn(6).setHeaderValue("Disponível?");
        }

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout pageManuntencaoLayout = new javax.swing.GroupLayout(pageManuntencao);
        pageManuntencao.setLayout(pageManuntencaoLayout);
        pageManuntencaoLayout.setHorizontalGroup(
            pageManuntencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageManuntencaoLayout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pageManuntencaoLayout.setVerticalGroup(
            pageManuntencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageManuntencaoLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        abasMenu.addTab("tab2", pageManuntencao);

        panelRound3.setBackground(new java.awt.Color(230, 232, 230));
        panelRound3.setAlignmentX(2.0F);
        panelRound3.setAlignmentY(2.0F);

        TableFrota2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nome", "CPF", "Multa?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableFrota2);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout pageClientesLayout = new javax.swing.GroupLayout(pageClientes);
        pageClientes.setLayout(pageClientesLayout);
        pageClientesLayout.setHorizontalGroup(
            pageClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageClientesLayout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pageClientesLayout.setVerticalGroup(
            pageClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageClientesLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        abasMenu.addTab("tab3", pageClientes);

        getContentPane().add(abasMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_frotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_frotaMousePressed
        abasMenu.setSelectedIndex(0);
        ColorOP.AnimarFrota();
    }//GEN-LAST:event_lbl_frotaMousePressed

    private void lbl_manuntencaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manuntencaoMousePressed
        abasMenu.setSelectedIndex(1);
        ColorOP.AnimarManuntencao();
    }//GEN-LAST:event_lbl_manuntencaoMousePressed

    private void lbl_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clientesMousePressed
        abasMenu.setSelectedIndex(2);
        ColorOP.AnimarClientes();
    }//GEN-LAST:event_lbl_clientesMousePressed

    private void btt_frotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_frotaMousePressed
        abasMenu.setSelectedIndex(0);
        ColorOP.AnimarFrota();
    }//GEN-LAST:event_btt_frotaMousePressed

    private void btt_manutencaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_manutencaoMousePressed
        abasMenu.setSelectedIndex(1);
        ColorOP.AnimarManuntencao();
    }//GEN-LAST:event_btt_manutencaoMousePressed

    private void btt_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_clientesMousePressed
        abasMenu.setSelectedIndex(2);
        ColorOP.AnimarClientes();
    }//GEN-LAST:event_btt_clientesMousePressed

    private void lbl_sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sairMousePressed
        System.exit(0);
    }//GEN-LAST:event_lbl_sairMousePressed

    private void btt_sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_sairMousePressed
        System.exit(0);
    }//GEN-LAST:event_btt_sairMousePressed

    private void TSearchFrotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSearchFrotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSearchFrotaActionPerformed

    private void TFEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEstadoActionPerformed

    private void FbttnSalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FbttnSalvarMousePressed
        // Obter a instância do repositório de carros
        RepoCarro repoCarro = RepoCarro.getInstance();

        // Verificar se já existe um carro com a mesma placa
        String placa = TFPlaca.getText();
        Carro carroExistente = repoCarro.obj("placa", placa);

        // Validação para não deixar dados em branco
        if (TFMarca.getText().equals("") || TFModelo.getText().equals("") || TFPlaca.getText().equals("")
                || TFValor.getText().equals("") || TFAno.getText().equals("")) {
            // Se qualquer uma dessas caixas estiverem em branco, mostrar mensagem.
            JOptionPane.showMessageDialog(this, "Por favor, preencha todas as caixas.");
        } else if (carroExistente != null) {
            // Se já existe um carro com a mesma placa, atualize os dados
            System.out.println("Carro com a mesma placa encontrado. Atualizando...");

            // Atualizar os dados do carro existente
            carroExistente.set("marca", TFMarca.getText());
            carroExistente.set("modelo", TFModelo.getText());
            carroExistente.set("ano", Integer.parseInt(TFAno.getText()));
            carroExistente.set("valor", Integer.parseInt(TFValor.getText()));
            carroExistente.set("estado", TFEstado.getSelectedItem().toString());

            // Atualizar a tabela
            addRowToTableFrota();

            // Mensagem de sucesso
            JOptionPane.showMessageDialog(this, "Carro atualizado com sucesso!");
        } else {
            // Se não existe um carro com a mesma placa, adicionar um novo carro
            System.out.println("Nenhum carro com a mesma placa encontrado. Adicionando novo carro...");

            // Criar um novo objeto Carro com os dados inseridos
            String marca = TFMarca.getText();
            String modelo = TFModelo.getText();
            int ano = Integer.parseInt(TFAno.getText()); // Converter o ano para int
            int valor = Integer.parseInt(TFValor.getText()); // Converter o valor para int
            String estado = TFEstado.getSelectedItem().toString();

            // Adicionar o carro ao repositório
            repoCarro.add(marca, modelo, ano, placa);

            // Definir o valor e o estado do carro
            Carro novoCarro = repoCarro.obj("placa", placa); // Recuperar o carro adicionado
            novoCarro.set("valor", valor);
            novoCarro.set("estado", estado);

            // Atualizar a tabela
            addRowToTableFrota();

            // Mensagem de sucesso
            JOptionPane.showMessageDialog(this, "Carro adicionado com sucesso!");

            // Limpar os campos após a inserção
            TFMarca.setText("");
            TFModelo.setText("");
            TFPlaca.setText("");
            TFAno.setText("");
            TFValor.setText("");
            TFEstado.setSelectedIndex(0); // Voltar para o estado padrão
        }

        // Verificação: Imprimir o conteúdo do repositório no console
        System.out.println("Carros no repositório:");
        for (Carro carro : repoCarro.src()) {
            System.out.println(carro);
        }
    }//GEN-LAST:event_FbttnSalvarMousePressed

    private void FbttnDeletarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FbttnDeletarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FbttnDeletarMousePressed


   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FTitulo;
    private javax.swing.JLabel FTitulo1;
    private Panel_redondo.PanelRound FbttnDeletar;
    private Panel_redondo.PanelRound FbttnSalvar;
    private gui.componentes.PanelGradient FiconeTitulo;
    private javax.swing.JLabel FlblDeletar;
    private javax.swing.JLabel FlblSalvar;
    private javax.swing.JPanel Menu;
    private javax.swing.JTextField TFAno;
    private javax.swing.JComboBox<String> TFEstado;
    private javax.swing.JTextField TFMarca;
    private javax.swing.JTextField TFModelo;
    private javax.swing.JTextField TFPlaca;
    private javax.swing.JTextField TFValor;
    private javax.swing.JPanel TSFrotaClear;
    private javax.swing.JTextField TSearchFrota;
    private javax.swing.JTable TableFrota;
    private javax.swing.JTable TableFrota1;
    private javax.swing.JTable TableFrota2;
    private javax.swing.JTabbedPane abasMenu;
    public static gui.componentes.PanelGradient btt_clientes;
    public static gui.componentes.PanelGradient btt_frota;
    public static gui.componentes.PanelGradient btt_manutencao;
    public static gui.componentes.PanelGradient btt_sair;
    private Panel_redondo.PanelRound fPainelFiltro;
    private Panel_redondo.PanelRound fPainelFrota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlacaa;
    private javax.swing.JLabel lblValor;
    public static javax.swing.JLabel lbl_clientes;
    public static javax.swing.JLabel lbl_frota;
    public static javax.swing.JLabel lbl_manuntencao;
    public static javax.swing.JLabel lbl_sair;
    private javax.swing.JPanel pageClientes;
    private javax.swing.JPanel pageFrota;
    private javax.swing.JPanel pageManuntencao;
    private Panel_redondo.PanelRound panelRound2;
    private Panel_redondo.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}

